### ISSUE TITLE
Internal Wikipages do not show up in current version of DokuWiki (Greebo)

### ISSUE THREAD

**Issue by igittigitt** [giterlizzi/dokuwiki-template-bootstrap3#448]
After installing and switching to the bootstrap3 template on a current Dokuwiki installation (fresh) the internal pages like Admin, Sitemap, etc. are no longer visible.

**Comment by giterlizzi** [comment]
Hi,
Can you see errors in Apache error_log?

**Comment by scorp1711** [comment]
Hi,
I see the same error when opening internal pages.

Here is the nginx error.log:
```
2020/01/06 11:06:26 [error] 29529#29529: *431 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function dokuwiki\template\bootstrap3\simplexml_load_file() in /var/www/dokuwiki/lib/tpl/bootstrap3/Template.php:2530
Stack trace:
#0 /var/www/dokuwiki/lib/tpl/bootstrap3/Template.php(94): dokuwiki\template\bootstrap3\Template->normalizeContent('<h1 class="sect...')
#1 /var/www/dokuwiki/inc/events.php(229): dokuwiki\template\bootstrap3\Template->contentHandler(Object(Doku_Event), NULL)
#2 /var/www/dokuwiki/inc/events.php(70): Doku_Event_Handler->process_event(Object(Doku_Event), 'BEFORE')
#3 /var/www/dokuwiki/inc/events.php(106): Doku_Event->advise_before(true)
#4 /var/www/dokuwiki/inc/events.php(256): Doku_Event->trigger('ptln', true)
#5 /var/www/dokuwiki/inc/template.php(85): trigger_event('TPL_CONTENT_DIS...', '\n<h1 class="sec...', 'ptln')
#6 /var/www/dokuwiki/lib/tpl/bootstrap3/main.php(111): tpl_content(false)
#7 /var/www/dokuwiki/inc/actions.php(27): include('/var/www/dokuwi...')
#8 /var/www/dokuwiki/doku.php(120): act_dispatch()
#9 {" while reading upstream, client: xx.xx.xx.xx, server: example.com, request: "GET /doku.php?id=start&do=admin&page=config HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "example.com"
```

**Comment by giterlizzi** [comment]
Seems missing ``php-xml`` module.

Please install the PHP module and restart nginx and or PHP-FPM daemons.
Sembra mancante il modulo `` php-xml``.
Joseph

**Comment by scorp1711** [comment]
Thanks for pointing me in the right direction, I thought I had installed php-xml, but it was missing for the php version used.

**Comment by giterlizzi** [comment]
;)

**Comment by igittigitt** [comment]
Great, thanks! Isn't it possible to write code to check for such dependencies after plugin installation and gives an errormessage?
