### ISSUE TITLE
Plugin translation compatibility

### ISSUE THREAD

**Issue by anfray** [giterlizzi/dokuwiki-template-bootstrap3#595]
### Description

We  can't update the Translation plugin as its last version does not seem to be compatible with  Bootstrap3 or may be vice versa :-) It seems that the getTransItem() function no longer exists in the helper.php file of  plugin translation.

### Steps to reproduce

1. upgrade to last version of Translation
2. 
3. 

**Expected behavior:** [What you expected to happen]

Everything works

**Actual behavior:** [What actually happened]

Error

![Capture d’écran 2023-05-26 à 13 44 32](https://github.com/giterlizzi/dokuwiki-template-bootstrap3/assets/18534298/1628ac9f-39a1-44b9-ad29-fed08ef8234a)

### Versions

* [Bootstrap3 Template]   v2022-07-27
* [DokuWiki]                      2023-04-04a "Jack Jackrum"
* [Plugins]      Translation 2021-08-23
* [PHP]           PHP 8.1.2-1ubuntu2.11
* [Browser]     Firefox

### Screenshots or Logs

2023-05-26 11:44:18Error: Call to undefined method helper_plugin_translation::**getTransItem()**/var/www/html/cemjazz/lib/tpl/bootstrap3/tpl/translation.php(31)
    #0 /var/www/html/cemjazz/lib/tpl/bootstrap3/tpl/navbar.php(89): include_once()
    #1 /var/www/html/cemjazz/lib/tpl/bootstrap3/main.php(51): require_once('...')
    #2 /var/www/html/cemjazz/inc/actions.php(27): include('...')
    #3 /var/www/html/cemjazz/doku.php(126): act_dispatch()
    #4 {main}

### Sample page or snippet
N.A.

**Comment by anfray** [comment]
Fixed in the dev branch
