### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by hruettimann** [giterlizzi/dokuwiki-template-bootstrap3#601]
### Description

Some of the icons in the Bootstrap3 theme are not displayed in the browser.

### Steps to reproduce

1. Download and install Bootstrap3 for our DokuWiki install (on our hosted web server)
3. Select the Bootstrap3 theme in DokuWiki

**Expected behavior:**
Bootstrap icons expected to be displayed.

**Actual behavior:**
Bootstrap icons not being displayed.

### Versions

* dokuwiki-template-bootstrap3 v2022-07-27 (stable/20220727), latest stable release
* DokuWiki 2023-04-04a "Jack Jackrum", latest stable release
* DW2PDF Plugin, iframe Plugin, Move Plugin, Wrap Plugin, HTMLOk Plugin, CSV Plugin, Tag Plugin
* PHP v8.2
* Google Chrome, Brave Browser, Vivaldi, Microsoft Edge, Apple Safari, Epiphany, Firefox

### Screenshots or Logs

**Screenshot Missing Editing Icons:**
<img width="859" alt="bootstrap3_missing-icons_editing" src="https://github.com/giterlizzi/dokuwiki-template-bootstrap3/assets/18068155/2e7bf98c-b6e2-4ab7-8362-9dfb9b9ced73">

**Screenshot Search Field and User Tools:**
<img width="454" alt="bootstrap3_missing-icons_search-and-tools" src="https://github.com/giterlizzi/dokuwiki-template-bootstrap3/assets/18068155/fd6430e2-6860-4b98-9d3c-29a8d2b0cbfd">

**DokuWiki Logs:**

2023-11-16 12:51:43
E_WARNING: Trying to access array offset on value of type null
/srv/www/vhosts/our-domain-name/subdomains/wiki/httpdocs/inc/Debug/DebugHelper.php(90)
#0 /srv/www/vhosts/our-domain-name/subdomains/wiki/httpdocs/inc/Debug/DebugHelper.php(90): dokuwiki\ErrorHandler::errorHandler()
#1 /srv/www/vhosts/our-domain-name/subdomains/wiki/httpdocs/inc/Debug/PropertyDeprecationHelper.php(83): dokuwiki\Debug\DebugHelper::dbgDeprecatedProperty()
#2 /srv/www/vhosts/our-domain-name/subdomains/wiki/httpdocs/lib/tpl/bootstrap3/iconify.php(82): dokuwiki\Cache\Cache->__set()
#3 {main}
2023-11-16 12:52:01
E_WARNING: Undefined array key 1
/srv/www/vhosts/our-domain-name/subdomains/wiki/httpdocs/inc/Debug/DebugHelper.php(52)
#0 /srv/www/vhosts/our-domain-name/subdomains/wiki/httpdocs/inc/Debug/DebugHelper.php(52): dokuwiki\ErrorHandler::errorHandler()
#1 /srv/www/vhosts/our-domain-name/subdomains/wiki/httpdocs/inc/cache.php(15): dokuwiki\Debug\DebugHelper::dbgDeprecatedFunction()
#2 /srv/www/vhosts/our-domain-name/subdomains/wiki/httpdocs/lib/tpl/bootstrap3/iconify.php(81): cache->__construct()
#3 {main}
2023-11-16 12:52:01
E_WARNING: Trying to access array offset on value of type null
/srv/www/vhosts/our-domain-name/subdomains/wiki/httpdocs/inc/Debug/DebugHelper.php(66)
#0 /srv/www/vhosts/our-domain-name/subdomains/wiki/httpdocs/inc/Debug/DebugHelper.php(66): dokuwiki\ErrorHandler::errorHandler()
#1 /srv/www/vhosts/our-domain-name/subdomains/wiki/httpdocs/inc/cache.php(15): dokuwiki\Debug\DebugHelper::dbgDeprecatedFunction()
#2 /srv/www/vhosts/our-domain-name/subdomains/wiki/httpdocs/lib/tpl/bootstrap3/iconify.php(81): cache->__construct()
#3 {main}
2023-11-16 12:52:01
E_WARNING: Undefined array key 1
/srv/www/vhosts/our-domain-name/subdomains/wiki/httpdocs/inc/Debug/DebugHelper.php(89)
#0 /srv/www/vhosts/our-domain-name/subdomains/wiki/httpdocs/inc/Debug/DebugHelper.php(89): dokuwiki\ErrorHandler::errorHandler()
#1 /srv/www/vhosts/our-domain-name/subdomains/wiki/httpdocs/inc/Debug/PropertyDeprecationHelper.php(83): dokuwiki\Debug\DebugHelper::dbgDeprecatedProperty()
#2 /srv/www/vhosts/our-domain-name/subdomains/wiki/httpdocs/lib/tpl/bootstrap3/iconify.php(82): dokuwiki\Cache\Cache->__set()
#3 {main}
2023-11-16 12:52:01
E_WARNING: Trying to access array offset on value of type null
/srv/www/vhosts/our-domain-name/subdomains/wiki/httpdocs/inc/Debug/DebugHelper.php(90)
#0 /srv/www/vhosts/our-domain-name/subdomains/wiki/httpdocs/inc/Debug/DebugHelper.php(90): dokuwiki\ErrorHandler::errorHandler()
#1 /srv/www/vhosts/our-domain-name/subdomains/wiki/httpdocs/inc/Debug/PropertyDeprecationHelper.php(83): dokuwiki\Debug\DebugHelper::dbgDeprecatedProperty()
#2 /srv/www/vhosts/our-domain-name/subdomains/wiki/httpdocs/lib/tpl/bootstrap3/iconify.php(82): dokuwiki\Cache\Cache->__set()
#3 {main}
2023-11-16 12:52:01
E_WARNING: Trying to access array offset on value of type null
/srv/www/vhosts/our-domain-name/subdomains/wiki/httpdocs/inc/Debug/DebugHelper.php(90)
#0 /srv/www/vhosts/our-domain-name/subdomains/wiki/httpdocs/inc/Debug/DebugHelper.php(90): dokuwiki\ErrorHandler::errorHandler()
#1 /srv/www/vhosts/our-domain-name/subdomains/wiki/httpdocs/inc/Debug/PropertyDeprecationHelper.php(83): dokuwiki\Debug\DebugHelper::dbgDeprecatedProperty()
#2 /srv/www/vhosts/our-domain-name/subdomains/wiki/httpdocs/lib/tpl/bootstrap3/iconify.php(82): dokuwiki\Cache\Cache->__set()
#3 {main}

**Comment by akhzz905** [comment]
Refer to #597

**Comment by hruettimann** [comment]
> Refer to #597

Thank you! This helped me resolve the issue, the icons now show up again!
