### ISSUE TITLE
after updated to dokuwiki 2024-02-06 "Kaos iconify.php returns error

### ISSUE THREAD

**Issue by ittun55** [giterlizzi/dokuwiki-template-bootstrap3#606]
### Description

[Description of the bug or feature]

### Steps to reproduce

1. [First Step]

  update to dokuwiki 2024-02-06 "Kaos" 

2. [Second Step]

  all icons presented by iconify.php disappeared.

**Expected behavior:** [What you expected to happen]

  all icons presented by iconify.php would be appeared.

**Actual behavior:** [What actually happened]

### Versions

* [Bootstrap3 Template]
  * 
* [DokuWiki]
  * 2024-02-06 "Kaos" 
* [Plugins]
* [PHP]
* [Browser]

### Screenshots or Logs

/data/log/error/2024-02-07.log

```
2024-02-06 16:44:10     /var/repos/burdock/bld.wws.jp/inc/Debug/DebugHelper.php(90)     E_WARNING: Trying to access array offset on value of type null
  #0 /var/repos/burdock/bld.wws.jp/inc/Debug/DebugHelper.php(90): dokuwiki\ErrorHandler::errorHandler()
  #1 /var/repos/burdock/bld.wws.jp/inc/Debug/PropertyDeprecationHelper.php(83): dokuwiki\Debug\DebugHelper::dbgDeprecatedProperty()
  #2 /var/repos/burdock/bld.wws.jp/lib/tpl/bootstrap3/iconify.php(82): dokuwiki\Cache\Cache->__set()
  #3 {main}
```

### Sample page or snippet

[Paste your sample DokuWiki page or snippet using MarkDown code syntax]

**Comment by ittun55** [comment]
I found it was already fixed
