### ISSUE TITLE
Dokuwiki farm : Error: Call to a member function setExtension() on null

### ISSUE THREAD

**Issue by Seplaenohr** [giterlizzi/dokuwiki-template-bootstrap3#613]
### Description

Hi, I have installed dokuwiki farmer and animals with the Farmer Plugin on Kaos version.
Bootstrap3 is installed and activated as template on the farmer.

When I go to the animal site and log, an error message appare near the administration menu (top right). 

If I activate another template for the animal (like dokuwiki default template) everything goes fine.

### Steps to reproduce

1. Install dokuwiki with farmer and animal (with farmer plugin)
2. Activate bootstrap3 on the animal
3. Login in the animal with admin account

**Expected behavior:** 

On the top right of the page, admin menus are accessible. When I choose an option, like administration, the corresponding page should appeare.

**Actual behavior:** [What actually happened]

On the top right of the page, admin menus are accessible but an error message appeare too :

`Error: Call to a member function setExtension() on null
An unforeseen error has occured. This is most likely a bug somewhere.
More info has been written to the DokuWiki error log.`

When I choose option, like administration, nothing append.

### Versions

* [Bootstrap3 Template] the last
* [DokuWiki] Kaos
* [Plugins] Farmer, Bootstrap3, many other
* [PHP] 7.4
* [Browser] Firefox

### Screenshots or Logs
Screenshots  : ![2024-10-18 11_50_58-Window](https://github.com/user-attachments/assets/f43f4644-14e6-4b24-9860-ca75e23b1a93)

The dokuwiki error log contains :

`2024-10-17 20:02:29 /var/www/html/doku_farmer/lib/tpl/bootstrap3/tpl/menu-user.php(47)
Error: Call to a member function setExtension() on null
#0 /var/www/html/doku_farmer/lib/tpl/bootstrap3/tpl/navbar.php(193): include_once()
#1 /var/www/html/doku_farmer/lib/tpl/bootstrap3/main.php(51): require_once('/var/www/html/d...')
#2 /var/www/html/doku_farmer/inc/actions.php(30): include('/var/www/html/d...')
#3 /var/www/html/doku_farmer/doku.php(131): act_dispatch()
#4 {main}`

### Sample page or snippet

[Paste your sample DokuWiki page or snippet using MarkDown code syntax]

**Comment by michielsebastiaan** [comment]
Same happens here on a regular new install. Yesterday a new download of dokuwiki without farming/animals. I am fairly positive one of my plugins could be a culprit. But this year I will not be able to spend time for troubleshooting. (As in a clean installation without plugins and adding them one by one)

**Comment by giterlizzi** [comment]
Hi, i applied a FIX.
Can you reinstall the template ?

Thanks!

**Comment by michielsebastiaan** [comment]
Hello Guiseppe,
Many thanks for your fast reply (And your long-time support on this template)

I can confirm it did solve the issue for me when I did another clean installation of Dokuwiki, 
Then this template and tried. It works again.

@Seplaenohr Please see if this fix also works for you.

Merry Christmas in advance.

**Comment by Seplaenohr** [comment]
Hello,

Thanks for your answers.

The new version of the template works like a charm !

Kind regards
